### ISSUE TITLE
Disabling testing when executing 'make' 

### ISSUE THREAD

**Issue by omerbn** [taocpp/taopq#20]
How do I do it? :)

**Comment by ColinH** [comment]
Have you tried `make compile` instead of `make`?

**Comment by omerbn** [comment]
I haven't. i'm noob in `make` procedure (working c/c++ on linux)   :)

So after running `make compile`, I need to copy `build/lib/libtaopq.a` to `/usr/local/lib` and `build/src/lib/pq` to 'usr/local/include/` ?
