### ISSUE TITLE
Missing byteswap.h on MSVC and macOS

### ISSUE THREAD

**Issue by emmenlau** [taocpp/taopq#23]
On MSVC and macOS I get build errors due to missing include `byteswap.h`, i.e.
```
C:\builds\taopq\include\tao/pq/internal/parameter_binary_traits.hpp(13): fatal error C1083: Cannot open include file: 'byteswap.h': No such file or directory
```

The docs only mention this header on glibc systems. Should I look for a drop-in replacement for other platforms?

**Comment by ColinH** [comment]
On macOS perhaps `machine/endian.h` or `libkern/OSByteOrder.h` could be used instead. We also have `endian.hpp` in the PEGTL which seems to work everywhere.

**Comment by d-frey** [comment]
I'll take care of it as soon as I find some time.

**Comment by emmenlau** [comment]
Thanks @d-frey !

**Comment by d-frey** [comment]
Should be fixed now.

**Comment by emmenlau** [comment]
Thanks, I confirm this works on macOS and MSVC!
