### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by uilianries** [taocpp/taopq#24]
As you can see, the current CI status is not okay.

I want to check and fix it later.

**Comment by d-frey** [comment]
OK, thanks, but it might also be my fault as a result of merging the binary parameter branch. I hope to find some time at the weekend to fix a couple of things, e.g. the MSVC support.

**Comment by uilianries** [comment]
Nice! :muscle:

**Comment by d-frey** [comment]
CI is fixed now.

Can we remove some of the Conan CI jobs from TravisCI / AppVeyor now that you created taocpp/conan-center-index? Or is this too early?

**Comment by uilianries** [comment]
Yes, totally. I 'll do it today later. Thanks for remember.
