### ISSUE TITLE
Clean cmake failing (visual studio 2017)

### ISSUE THREAD

**Issue by phanomgames** [taocpp/taopq#26]
As of the latest commit in master (haven't tried earlier ones)

CMake Error at W:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY
  PostgreSQL_INCLUDE_DIR PostgreSQL_TYPE_INCLUDE_DIR)		W:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake	137	

Took a look in taopq-master\taopq-master\cmake\taopqConfig.cmake.in

and it seems like it specifically needs PostgreSQL 9.6.9. Is that the case? I've got postgresql 12 installed.

Either way, figured I'd try the conan route, and the package isn't found in the remote.

taocpp-taopq/20200215: Not found in local cache, looking in remotes...
taocpp-taopq/20200215: Trying with 'conan-center'...
ERROR: Unable to find 'taocpp-taopq/20200215' in remotes

I've got the libpq libraries built, but not sure how to proceed,

**Comment by uilianries** [comment]
First, you need to check the available versions:

    conan search -r conan-center taocpp-taopq

And, install:

    conan install -r conan-center taocpp-taopq/20200222@

If you want the latest date available, please, file an issue to taocpp-taopq/20200222

Anyway, Taopq should be able to run with libpq 11, which is available on Conan Center Index.

**Comment by d-frey** [comment]
@uilianries IIRC you also added the taopqConfig.cmake.in, and it explicitly specifies a version. CMake is supposed to also find "compatible" versions, but that seems to be fragile. Should we just remove the version number?

**Comment by phanomgames** [comment]
FWIW I used the conan -r solution and it worked fine.
