### ISSUE TITLE
XMake packaging?

### ISSUE THREAD

**Issue by Arteneko** [taocpp/taopq#35]
Hello, I was wondering if you would accept to package this library on the xmake build system ?

That would make xmake-based development easier.

Thanks!

**Comment by d-frey** [comment]
There are too many build systems out there and accepting more of those into our repository would be a maintenance nightmare - we would need to learn and maintain all those systems, plus adding CI jobs for all of them. We therefore focus on a Makefile (which Colin and me are using ourselfs) and for most users and for portability, we provide CMake support (as CMake seems to be the most widespread system currently available). And CMake is already causing us enough headaches :)

That said, if you want to package our library outside of our repository, please feel free to do so.
