### ISSUE TITLE
Vector doesn't seem to conform to has_reserve

### ISSUE THREAD

**Issue by own2pwn** [taocpp/taopq#36]
https://github.com/taocpp/taopq/blob/40d28760e32466c6ff2d94f1cb67b486e5a37d18/include/tao/pq/result.hpp#L151

```
using result_t = std::tuple<int, int>;
auto rows = resp.vector<result_t>();
```

resulting vector's size != it's capacity

**Comment by d-frey** [comment]
The standard only guarantees size <= capacity. What are the actual values you are seeing?

Also, I don't understand what this has to do with `has_reserve`. Could you be more specific?

**Comment by own2pwn** [comment]
Sorry for the delayed response. I thought it is expected that `has_reserve < vector <E> >` would result in `true` so we fall in and allocate memory in advance. But in my case that's not true

**Comment by d-frey** [comment]
Ah, now I see. And you are right, `has_reserve` is broken and there is no unit test for it.
