### ISSUE TITLE
Reference to "Table of Content" in README.md is not valid

### ISSUE THREAD

**Issue by gim** [taocpp/taopq#54]
README.md links to `doc/TOC.md` on [line 63] (https://github.com/taocpp/taopq/blob/b1708782063b0e2e64800cd27ff125eba02afb10/README.md?plain=1#L63) which is not currently present in the tree.

The rest of the links under "Documentation" are to valid locations.

**Comment by d-frey** [comment]
Just some quick feedback: Yes, you are right. I'm working on it, but I ran out of time today, will fix it soon.
