### ISSUE TITLE
error: ‘null’ is not a member of ‘tao::pq::result_traits<int>’

### ISSUE THREAD

**Issue by kevin143carr** [taocpp/taopq#55]
I am getting these errors when I build!  I have done a fresh clone.  -- Thanks Kevin!

include/tao/pq/row.hpp: In instantiation of ‘T tao::pq::row::get(std::size_t) const [with T = int; std::size_t = long unsigned int]’:
include/tao/pq/row.hpp:299:40:   required from ‘T tao::pq::field::as() const [with T = int]’
src/test/pq/result.cpp:156:10:   required from here
include/tao/pq/row.hpp:224:50: error: ‘null’ is not a member of ‘tao::pq::result_traits<int>’
                   return result_traits< T >::null();

include/tao/pq/row.hpp:224:50:   required from ‘T tao::pq::row::get(std::size_t) const [with T = std::tuple<int>; std::size_t = long unsigned int]’
include/tao/pq/row.hpp:247:29:   required from ‘T tao::pq::row::as() const [with T = std::tuple<int>]’
include/tao/pq/result.hpp:242:40:   required from ‘T tao::pq::result::as() const [with T = std::tuple<int>]’
include/tao/pq/result.hpp:263:43:   required from ‘auto tao::pq::result::tuple() const [with Ts = {int}]’
src/test/pq/result.cpp:52:4:   required from here
include/tao/pq/result_traits_tuple.hpp:24:55: error: ‘null’ is not a member of ‘tao::pq::result_traits<int>’
       return std::tuple< T >( result_traits< T >::null() );

**Comment by d-frey** [comment]
What compiler version are you using? The error basically means that the `result_traits_has_null`-helper is giving the wrong answer or `if constexpr` is not working correctly on your system.

**Comment by kevin143carr** [comment]
Gcc 8.3.1 on CentOS 7

**Comment by d-frey** [comment]
Our CI job uses GCC 8.4.0. If you can't upgrade your compiler, can you try to create a minimal example based on `result_traits_has_null` and check whether it detects the existence of `null` correctly?

**Comment by kevin143carr** [comment]
Thanks for responding.  I will see about upgrading to 8.4.0.  I am rebuilding my dev environment now.  Otherwise perhaps you could provide me an example of what you are talking about.  I am not the greatest at C++ and I am simply trying to compile your library to use with another library.

**Comment by kevin143carr** [comment]
I upgraded to devtoolset9 and it built properly.  So I guess the issue is a C++ functionality not support with 8.3.1 -- Thanks!
