### ISSUE TITLE
Unable to use set_notification_handler

### ISSUE THREAD

**Issue by ajashford** [taocpp/taopq#58]
Hello,

I am trying to set a notification handler to listen for events. I have set up multiple channels and I have a notification handler who's signature is:

(XXXXX::XXXX is namespace blanked out)
void XXXXX::XXXX::Connection_Notification(const tao::pq::notification &message)

When I try to execute:

conn->set_notification_handler(Connection_Notification);

I am getting an error , "no instance of overload function tao::pq::connection::set_notification_handler matches the argument list (void(const tao::pq::notification &message))"

Any ideas what is wrong with the function signature I am providing? Thanks in advance.

**Comment by d-frey** [comment]
Can you copy-paste the exact and full error message?

**Comment by d-frey** [comment]
Without further feedback from your side I'm afraid there is nothing we can do. The only thing I can advise is to double-check that XXXX::XXXX:: is really just namespaces as you say and *not* a class/struct. If your method is a non-static member of a class/struct, it would explain why it's not a candidate, as it can only be called on an object, not as a free-standing function.

**Comment by ajashford** [comment]
Hi,

In my previous response, I did a std::bind and got things to compile up. It
was my mistake in that the compiler was giving the correct error in that
using the function directly, it had the wrong signature since it specified
a named input variable. By binding my function to a std:: function, I could
then use that. Sorry for report a non-issue that was because of my mistake.
Thanks to you and your team for the support.
