### ISSUE TITLE
question: calling execute on a threadpool

### ISSUE THREAD

**Issue by TennisBowling** [taocpp/taopq#61]
can I call `execute` on a threadpool?

ex.
```c++
const auto conn = tao::pq::connection_pool::create("dbname=postgres user=postgres password=postgres");
conn->execute("CREATE TABLE IF NOT EXISTS fcu_data (VALUE TEXT);");
```
instead of
`conn->connection()->execute("CREATE TABLE IF NOT EXISTS fcu_data (VALUE TEXT);");`
?

**Comment by d-frey** [comment]
Yes, see https://github.com/taocpp/taopq/blob/main/doc/Connection-Pool.md#executing-statements

And it's not a thread pool, it's a connection pool. But you can make the above calls from multiple threads if you like.
