### ISSUE TITLE
Aggregate Support optimization

### ISSUE THREAD

**Issue by gelijian** [taocpp/taopq#73]
how about using pfr to implement this feature

**Comment by gelijian** [comment]
the link of pfr project: https://github.com/boostorg/pfr

**Comment by d-frey** [comment]
There is no reason to add a dependency to another library (other than `libpq`, of course), not even if we were to copy the code for PFR into our repository. PFR is multiple headers with 5000+ lines of code to replace a single header of ours with ~150 lines of code. And I won't even start on the complexity of the implementation. So, no, that provides no benefit and I will absolutely not do that.

**Comment by gelijian** [comment]
Thanks for your reply. Is it possible to increase the limit of the number of struct field from 26 to some larger number like 128.

**Comment by d-frey** [comment]
I've raised the limit to 99 for now. Is this sufficient or do you need more?

**Comment by gelijian** [comment]
Yes, thanks a lot
