### ISSUE TITLE
Deprecated: char_traits<T> in LLVM 18

### ISSUE THREAD

**Issue by kostya416** [taocpp/taopq#76]
I got this warning and next thing I found that LLVM 19 will remove it completely making it impossible to build taopq with this toolchain. Any chance this could be fixed?

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme
I put the necessary dlls in the archive

**Comment by kostya416** [comment]
what dlls? It has to be fixed at the source level. Either char_trait provided or use of it replaced. Btw your zip contains virus.

**Comment by d-frey** [comment]
I compiled with clang 18.1.8 and I don't see any warning. Can you post the complete error message and, if possible, a small but complete example program?

**Comment by kostya416** [comment]
If it helps here is example of warning (I edited out leading parts of the paths):

[1/93] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/internal/demangle.cpp.obj
[2/93] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/field.cpp.obj
In file included from 3rd-party/taopq/src/lib/pq/field.cpp:5:
In file included from 3rd-party/taopq/include/tao/pq/field.hpp:10:
In file included from LLVM/current/include/c++/v1/string:625:
In file included from LLVM/current/include/c++/v1/string_view:213:
LLVM/current/include/c++/v1/__fwd/string_view.h:22:41: warning: 'char_traits<std::byte>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 19, so please migrate off of it. [-Wdeprecated-declarations]
   22 | template <class _CharT, class _Traits = char_traits<_CharT> >
      |                                         ^
3rd-party/taopq/include/tao/pq/binary.hpp:15:29: note: in instantiation of default argument for 'basic_string_view<std::byte>' required here
   15 |    using binary_view = std::basic_string_view< std::byte >;
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
LLVM/current/include/c++/v1/__string/char_traits.h:81:8: note: 'char_traits<std::byte>' has been explicitly marked deprecated here
   81 | struct _LIBCPP_DEPRECATED_(
      |        ^
LLVM/current/include/c++/v1/__config:975:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
  975 | #      define _LIBCPP_DEPRECATED_(m) __attribute__((__deprecated__(m)))
      |                                                     ^
1 warning generated.

**Comment by kostya416** [comment]
Any info on progress?

**Comment by d-frey** [comment]
I was considering some options, but the only reasonable option is switching to C++20, as it has ´std::span´. I will update the code when I have some time.

**Comment by d-frey** [comment]
I have updated the code, but some things might not be final. Docs also need to be adapted. Please have a look and let me know if you see any problems or if you have any other feedback.

**Comment by kostya416** [comment]
Thank you so much for your efforts. Late evening here now, will be checking it first thing tomorrow morning.

**Comment by kostya416** [comment]
Project builds on Linux under LLVM-18 without warnings and seems to run fine so far.
I also tried LLVM-19 and it fails to build with following  warnings and errors:

building service popsvc
Consolidate compiler generated dependencies of target spdlog
Consolidate compiler generated dependencies of target taopq
[  1%] Building CXX object 3rd-party/spdlog/CMakeFiles/spdlog.dir/src/spdlog.cpp.o
[  2%] Building CXX object 3rd-party/spdlog/CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o
[  3%] Building CXX object 3rd-party/spdlog/CMakeFiles/spdlog.dir/src/color_sinks.cpp.o
[  4%] Building CXX object 3rd-party/spdlog/CMakeFiles/spdlog.dir/src/file_sinks.cpp.o
[  5%] Building CXX object 3rd-party/spdlog/CMakeFiles/spdlog.dir/src/async.cpp.o
[  5%] Building CXX object 3rd-party/spdlog/CMakeFiles/spdlog.dir/src/cfg.cpp.o
[  6%] Building CXX object 3rd-party/spdlog/CMakeFiles/spdlog.dir/src/bundled_fmtlib_format.cpp.o
[  7%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/connection.cpp.o
[  8%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/connection_pool.cpp.o
[  9%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/exception.cpp.o
[ 10%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/field.cpp.o
[ 11%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/internal/demangle.cpp.o
[ 12%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/internal/poll.cpp.o
[ 13%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/internal/printf.cpp.o
[ 14%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/internal/strtox.cpp.o
[ 14%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/large_object.cpp.o
[ 15%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/parameter_traits.cpp.o
[ 16%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/result.cpp.o
[ 17%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/result_traits.cpp.o
[ 19%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/table_field.cpp.o
[ 19%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/row.cpp.o
[ 21%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/table_row.cpp.o
[ 22%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/table_reader.cpp.o
[ 22%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/table_writer.cpp.o
[ 23%] Building CXX object 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/transaction.cpp.o
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/src/lib/pq/connection.cpp:5:
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/connection.hpp:28:
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:77:34: error: '...' must immediately precede declared identifier
   77 |                          const Ts...& ts )
      |                                  ^~~
      |                                       ...
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:79:52: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   79 |          const Oid types[] = { static_cast< Oid >( ts...[ Os ].template type< Is >() )... };
      |                                                    ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:80:41: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   80 |          const char* const values[] = { ts...[ Os ].template value< Is >()... };
      |                                         ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:81:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   81 |          const int lengths[] = { ts...[ Os ].template length< Is >()... };
      |                                  ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:82:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   82 |          const int formats[] = { ts...[ Os ].template format< Is >()... };
      |                                  ^
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/src/lib/pq/transaction.cpp:7:
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/connection.hpp:28:
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:77:34: error: '...' must immediately precede declared identifier
   77 |                          const Ts...& ts )
      |                                  ^~~
      |                                       ...
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:79:52: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   79 |          const Oid types[] = { static_cast< Oid >( ts...[ Os ].template type< Is >() )... };
      |                                                    ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:80:41: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   80 |          const char* const values[] = { ts...[ Os ].template value< Is >()... };
      |                                         ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:81:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   81 |          const int lengths[] = { ts...[ Os ].template length< Is >()... };
      |                                  ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:82:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   82 |          const int formats[] = { ts...[ Os ].template format< Is >()... };
      |                                  ^
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/src/lib/pq/table_row.cpp:5:
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/table_reader.hpp:25:
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:77:34: error: '...' must immediately precede declared identifier
   77 |                          const Ts...& ts )
      |                                  ^~~
      |                                       ...
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:79:52: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   79 |          const Oid types[] = { static_cast< Oid >( ts...[ Os ].template type< Is >() )... };
      |                                                    ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:80:41: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   80 |          const char* const values[] = { ts...[ Os ].template value< Is >()... };
      |                                         ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:81:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   81 |          const int lengths[] = { ts...[ Os ].template length< Is >()... };
      |                                  ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:82:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   82 |          const int formats[] = { ts...[ Os ].template format< Is >()... };
      |                                  ^
4 warnings and 1 error generated.
make[2]: *** [3rd-party/taopq/CMakeFiles/taopq.dir/build.make:76: 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/connection.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/src/lib/pq/connection_pool.cpp:5:
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/connection_pool.hpp:15:
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/connection.hpp:28:
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:77:34: error: '...' must immediately precede declared identifier
   77 |                          const Ts...& ts )
      |                                  ^~~
      |                                       ...
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:79:52: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   79 |          const Oid types[] = { static_cast< Oid >( ts...[ Os ].template type< Is >() )... };
      |                                                    ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:80:41: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   80 |          const char* const values[] = { ts...[ Os ].template value< Is >()... };
      |                                         ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:81:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   81 |          const int lengths[] = { ts...[ Os ].template length< Is >()... };
      |                                  ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:82:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   82 |          const int formats[] = { ts...[ Os ].template format< Is >()... };
      |                                  ^
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/src/lib/pq/table_writer.cpp:5:
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/table_writer.hpp:20:
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:77:34: error: '...' must immediately precede declared identifier
   77 |                          const Ts...& ts )
      |                                  ^~~
      |                                       ...
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:79:52: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   79 |          const Oid types[] = { static_cast< Oid >( ts...[ Os ].template type< Is >() )... };
      |                                                    ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:80:41: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   80 |          const char* const values[] = { ts...[ Os ].template value< Is >()... };
      |                                         ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:81:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   81 |          const int lengths[] = { ts...[ Os ].template length< Is >()... };
      |                                  ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:82:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   82 |          const int formats[] = { ts...[ Os ].template format< Is >()... };
      |                                  ^
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/src/lib/pq/table_writer.cpp:5:
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/table_writer.hpp:35:36: error: '...' must immediately precede declared identifier
   35 |                            const Ts...& ts )
      |                                    ^~~
      |                                         ...
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/table_writer.hpp:38:14: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   38 |          ( ( ts...[ Os ].template copy_to< Is >( buffer ), buffer += '\t' ), ... );
      |              ^
4 warnings and 1 error generated.
make[2]: *** [3rd-party/taopq/CMakeFiles/taopq.dir/build.make:286: 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/table_row.cpp.o] Error 1
4 warnings and 1 error generated.
make[2]: *** [3rd-party/taopq/CMakeFiles/taopq.dir/build.make:314: 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/transaction.cpp.o] Error 1
5 warnings and 2 errors generated.
4 warnings and 1 error generated.
make[2]: *** [3rd-party/taopq/CMakeFiles/taopq.dir/build.make:90: 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/connection_pool.cpp.o] Error 1
make[2]: *** [3rd-party/taopq/CMakeFiles/taopq.dir/build.make:300: 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/table_writer.cpp.o] Error 1
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/src/lib/pq/table_reader.cpp:5:
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/table_reader.hpp:25:
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:77:34: error: '...' must immediately precede declared identifier
   77 |                          const Ts...& ts )
      |                                  ^~~
      |                                       ...
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:79:52: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   79 |          const Oid types[] = { static_cast< Oid >( ts...[ Os ].template type< Is >() )... };
      |                                                    ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:80:41: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   80 |          const char* const values[] = { ts...[ Os ].template value< Is >()... };
      |                                         ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:81:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   81 |          const int lengths[] = { ts...[ Os ].template length< Is >()... };
      |                                  ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:82:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   82 |          const int formats[] = { ts...[ Os ].template format< Is >()... };
      |                                  ^
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/src/lib/pq/large_object.cpp:12:
In file included from /xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/connection.hpp:28:
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:77:34: error: '...' must immediately precede declared identifier
   77 |                          const Ts...& ts )
      |                                  ^~~
      |                                       ...
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:79:52: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   79 |          const Oid types[] = { static_cast< Oid >( ts...[ Os ].template type< Is >() )... };
      |                                                    ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:80:41: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   80 |          const char* const values[] = { ts...[ Os ].template value< Is >()... };
      |                                         ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:81:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   81 |          const int lengths[] = { ts...[ Os ].template length< Is >()... };
      |                                  ^
/xxx/source/popapi-cpp/3rd-party/taopq/include/tao/pq/transaction.hpp:82:34: warning: pack indexing is a C++2c extension [-Wc++26-extensions]
   82 |          const int formats[] = { ts...[ Os ].template format< Is >()... };
      |                                  ^
4 warnings and 1 error generated.
make[2]: *** [3rd-party/taopq/CMakeFiles/taopq.dir/build.make:188: 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/large_object.cpp.o] Error 1
4 warnings and 1 error generated.
make[2]: *** [3rd-party/taopq/CMakeFiles/taopq.dir/build.make:272: 3rd-party/taopq/CMakeFiles/taopq.dir/src/lib/pq/table_reader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:254: 3rd-party/taopq/CMakeFiles/taopq.dir/all] Error 2

**Comment by d-frey** [comment]
The first error (`const Ts...& ts`) is clearly a syntax error. Fixed.

The second warning (pack indexing is a C++2c extension) is weird. I did put it in a section guarded by `#if defined( __cpp_pack_indexing)`. Is this set even though the feature is *not* available? Seems like a bug in Clang 19 then...

**Comment by kostya416** [comment]
Yeah it does look like a bug in clang. That pack indexes feature is stated as available in Clang-19. I tried setting C++ standard to C++2c in my project explicitly but it still gives me a warning. the project builds and works however. For now I settled with adding -Wno-c++26-extensions to your cmaklists to suppress the warning. Again thanks so much for your efforts

**Comment by d-frey** [comment]
The warning you get actually mentions `-Wc++26-extensions`, which makes me wonder where that option is coming from and whether `-Wno-c++26-extensions` could get rid of it.

**Comment by d-frey** [comment]
I made some more changes, including checking whether C++26 is enabled or not (in addition to the feature check). You may be able to remove the `-Wno-C++26-extensions` flag.
